
import { TrendingJob, AnalysisResult, DetailedRecommendation, PersonalizedGuidanceResult } from '../types';

export const sampleTrendingJobs: TrendingJob[] = [
  {
    title: 'AI/ML Engineer',
    salaryRange: '₹15-25 LPA',
    growth: 'Hot',
    topIndustries: ['SaaS', 'FinTech', 'HealthTech'],
    keySkills: ['Python', 'TensorFlow', 'Cloud (AWS/GCP)'],
  },
  {
    title: 'Full Stack Developer',
    salaryRange: '₹10-18 LPA',
    growth: 'Growing',
    topIndustries: ['E-commerce', 'SaaS', 'Startups'],
    keySkills: ['React', 'Node.js', 'SQL/NoSQL'],
  },
  {
    title: 'Cloud Solutions Architect',
    salaryRange: '₹20-35 LPA',
    growth: 'Hot',
    topIndustries: ['IT Services', 'Enterprise Software', 'Banking'],
    keySkills: ['AWS', 'Azure', 'Terraform'],
  },
  {
    title: 'Data Scientist',
    salaryRange: '₹12-22 LPA',
    growth: 'Growing',
    topIndustries: ['Analytics', 'Retail', 'Consulting'],
    keySkills: ['SQL', 'Python', 'Machine Learning'],
  },
  {
    title: 'Cybersecurity Analyst',
    salaryRange: '₹8-15 LPA',
    growth: 'Growing',
    topIndustries: ['Banking', 'IT Services', 'Government'],
    keySkills: ['SIEM', 'Network Security', 'Pen Testing'],
  },
  {
    title: 'Product Manager',
    salaryRange: '₹18-30 LPA',
    growth: 'Stable',
    topIndustries: ['SaaS', 'Consumer Tech', 'B2B'],
    keySkills: ['Roadmapping', 'Agile', 'User Research'],
  },
];

export const sampleTopSkills: string[] = [
  'Artificial Intelligence',
  'Cloud Computing',
  'Data Structures & Algorithms',
  'Cybersecurity',
  'UI/UX Design',
  'Product Management',
  'Communication',
  'Adaptability',
];

export const sampleAnalysisResult: AnalysisResult = {
  jobTitle: 'Software Engineer (Demo)',
  summary: 'This is a sample analysis demonstrating the fallback mechanism. In a live scenario, this summary would be generated by analyzing real-time job postings scraped by the Python backend. It highlights the demand for strong foundational skills combined with modern cloud and DevOps practices.',
  trendingSkills: [
    { name: 'Data Structures & Algorithms', description: 'Core computer science principles remain critical.', relevance: 10 },
    { name: 'Cloud Computing (AWS/Azure)', description: 'Experience with major cloud platforms is highly sought after.', relevance: 9 },
    { name: 'Containerization (Docker)', description: 'Knowledge of container technologies is essential for modern development.', relevance: 8 },
  ],
  recommendedCourses: [
    { title: 'Mastering the Coding Interview: Data Structures + Algorithms', platform: 'Udemy', url: '#', description: 'A comprehensive course to solidify core programming fundamentals.' },
    { title: 'AWS Certified Solutions Architect - Associate', platform: 'Coursera', url: '#', description: 'Prepare for a key industry certification in cloud computing.' },
  ],
};

export const sampleDetailedRecommendation: DetailedRecommendation = {
  summary: "This is a sample career path demonstrating the fallback mechanism. It outlines a robust trajectory for a Software Engineer in India, starting with a strong foundation and progressing towards a leadership role.",
  growthPlan: {
    readinessScore: 78,
    kpis: [
      { name: "Technical Skill Alignment", score: 85, summary: "Your skills in core languages are strong." },
      { name: "Project Experience", score: 70, summary: "Projects are good but could showcase more complex, real-world problems." },
    ],
    actionItems: [
      { description: "Contribute to a mid-sized open-source project to demonstrate collaboration skills." },
      { description: "Build and deploy a full-stack application using a CI/CD pipeline." },
    ],
  },
  careerPath: [
    {
      title: "Software Development Engineer 1",
      duration: "Years 0-2",
      summary: "Focus on mastering core programming, contributing to the codebase, and learning team development practices.",
      skillsToMaster: ["Java/Python", "Spring Boot/Django", "SQL", "Git"],
      potentialSalary: "₹8-15 LPA",
      targetCompanies: [
        {
          companyName: "TCS (Digital)",
          roles: ["Assistant System Engineer"],
          estimatedPackageLPA: "₹7-9 LPA",
          requiredSkills: ["Java", "SQL", "Spring"],
        },
        {
          companyName: "Amazon",
          roles: ["SDE-1"],
          estimatedPackageLPA: "₹15-25 LPA+",
          requiredSkills: ["Data Structures", "Algorithms", "System Design Principles"],
        },
      ],
    },
    {
      title: "Senior Software Engineer",
      duration: "Years 2-5",
      summary: "Take ownership of features, mentor junior developers, and contribute to system design.",
      skillsToMaster: ["System Design", "Cloud Architecture (AWS)", "Microservices"],
      potentialSalary: "₹20-40 LPA",
    },
  ],
};

export const samplePersonalizedGuidance: PersonalizedGuidanceResult = {
  recommendedCourses: [
    { title: "Advanced Python for Web Development", platform: "Udemy", url: "#", reason: "To deepen your backend development skills beyond the basics." },
    { title: "React - The Complete Guide", platform: "Coursera", url: "#", reason: "Essential for building modern, interactive user interfaces." },
  ],
  jobPlatforms: [
    { name: "Naukri.com", url: "#", reason: "The largest platform for job listings in the Indian market." },
    { name: "LinkedIn Jobs", url: "#", reason: "Excellent for networking and finding roles at top product companies." },
  ],
};
